"""dispute created_date to create_date

Revision ID: 02ac5549012b
Revises: 102ae51e2a37
Create Date: 2024-10-09 17:38:30.740860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02ac5549012b'
down_revision: Union[str, None] = '102ae51e2a37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dispute', sa.Column('create_date', sa.Date(), nullable=True))
    op.drop_column('dispute', 'created_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dispute', sa.Column('created_date', sa.DATE(), nullable=True))
    op.drop_column('dispute', 'create_date')
    # ### end Alembic commands ###
