"""added Disputes

Revision ID: 102ae51e2a37
Revises: c6c4e161ad05
Create Date: 2024-10-09 17:26:15.358142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '102ae51e2a37'
down_revision: Union[str, None] = 'c6c4e161ad05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispute',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dispute_number', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.Date(), nullable=True),
    sa.Column('resolved_date', sa.Date(), nullable=True),
    sa.Column('associate', sa.String(length=100), nullable=True),
    sa.Column('resolution', sa.String(length=255), nullable=True),
    sa.Column('resolution_comments', sa.String(length=255), nullable=True),
    sa.Column('contact', sa.String(length=255), nullable=True),
    sa.Column('package_assoc', sa.String(length=250), nullable=True),
    sa.Column('reversal_reason', sa.String(length=255), nullable=True),
    sa.Column('reversal_amount', sa.Float(), nullable=True),
    sa.Column('reversal_transmitted', sa.DateTime(), nullable=True),
    sa.Column('charge_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['charge_number'], ['charge.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dispute')
    # ### end Alembic commands ###
