"""FillDetail style to string

Revision ID: 271a0ffd8e39
Revises: 6fe5990c6448
Create Date: 2024-10-28 14:45:49.914031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '271a0ffd8e39'
down_revision: Union[str, None] = '6fe5990c6448'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fill_detail', 'style',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=150),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fill_detail', 'style',
               existing_type=sa.String(length=150),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
