"""fixed calendar to charges relation

Revision ID: 40f1302edce5
Revises: b9cbe2bc9938
Create Date: 2024-10-30 11:02:15.502313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40f1302edce5'
down_revision: Union[str, None] = 'b9cbe2bc9938'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
