"""larger comment storage (725)

Revision ID: 477796550a45
Revises: 78f30792d536
Create Date: 2024-11-08 15:04:24.856541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '477796550a45'
down_revision: Union[str, None] = '78f30792d536'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_issue', 'comments',
               existing_type=mysql.VARCHAR(length=525),
               type_=sa.String(length=725),
               existing_nullable=True)
    op.alter_column('audit_trouble', 'comments',
               existing_type=mysql.VARCHAR(length=525),
               type_=sa.String(length=725),
               existing_nullable=True)
    op.alter_column('dispute', 'resolution_comments',
               existing_type=mysql.VARCHAR(length=525),
               type_=sa.String(length=725),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dispute', 'resolution_comments',
               existing_type=sa.String(length=725),
               type_=mysql.VARCHAR(length=525),
               existing_nullable=True)
    op.alter_column('audit_trouble', 'comments',
               existing_type=sa.String(length=725),
               type_=mysql.VARCHAR(length=525),
               existing_nullable=True)
    op.alter_column('audit_issue', 'comments',
               existing_type=sa.String(length=725),
               type_=mysql.VARCHAR(length=525),
               existing_nullable=True)
    # ### end Alembic commands ###
