"""added boolean trackers to cal and charge

Revision ID: 78f30792d536
Revises: 40f1302edce5
Create Date: 2024-10-31 14:05:39.464313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78f30792d536'
down_revision: Union[str, None] = '40f1302edce5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar', sa.Column('imported', sa.Boolean(), nullable=False))
    op.add_column('charge', sa.Column('pulled', sa.Boolean(), nullable=False))
    op.add_column('charge', sa.Column('imported', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('charge', 'imported')
    op.drop_column('charge', 'pulled')
    op.drop_column('calendar', 'imported')
    # ### end Alembic commands ###
