"""added calendar and relation to charges

Revision ID: b9cbe2bc9938
Revises: 271a0ffd8e39
Create Date: 2024-10-30 10:56:30.943432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9cbe2bc9938'
down_revision: Union[str, None] = '271a0ffd8e39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charge', sa.Column('calendar_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'charge', 'calendar', ['calendar_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'charge', type_='foreignkey')
    op.drop_column('charge', 'calendar_id')
    # ### end Alembic commands ###
