"""dispute resolved_date to resolve_date

Revision ID: c2fbf9668527
Revises: 02ac5549012b
Create Date: 2024-10-09 17:48:03.571983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2fbf9668527'
down_revision: Union[str, None] = '02ac5549012b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dispute', sa.Column('resolve_date', sa.Date(), nullable=True))
    op.drop_column('dispute', 'resolved_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dispute', sa.Column('resolved_date', sa.DATE(), nullable=True))
    op.drop_column('dispute', 'resolve_date')
    # ### end Alembic commands ###
