"""FillDetail upc to string

Revision ID: c390afbeb713
Revises: 
Create Date: 2024-10-09 11:52:02.538111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c390afbeb713'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fill_detail', 'upc',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=120),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fill_detail', 'upc',
               existing_type=sa.String(length=120),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
